#ifndef PSDFONTS_H_INCLUDED
#define PSDFONTS_H_INCLUDED

// 子程序处理 Photoshop格式(*.psd) 模块，收集psd格式字体信息
int psdFonts(int argc, char* argv[]);

// 搜索PSD文件缓存，把字体PsName装载到容器
bool SearchFontSet_PsnameToMap(const char* buffer, size_t count, map<string, size_t>& flag_map);



// 中文字体名和英文名对应表
static string FontsNameTable =
    "<儷黑 Pro> LiHei Pro Medium\n"
    "<儷宋 Pro> LiSong Pro Light\n"
    "<標楷體> BiauKai\n"
    "<標楷體> DFKai-SB\n"
    "<方正报宋_GBK> FZBSK--GBK1-0 FZBaoSong-Z04\n"
    "<方正报宋繁体> FZBaoSong-Z04T FZXLFW FZXLFW—GB1-0\n"
    "<方正报宋简体> FZBaoSong-Z04S FZBSJW FZBSJW—GB1-0\n"
    "<方正北魏楷书_GBK> FZBWKSK--GBK1-0 FZBeiWeiKaiShu-Z15\n"
    "<方正北魏楷书繁体> FZBeiWeiKaiShu-Z15T FZBWKSFW—GB1-0 FZBWKSFW\n"
    "<方正北魏楷书简体> FZBeiWeiKaiShu-Z15S FZBWKSJW—GB1-0 FZBWKSJW\n"
    "<方正彩云_GBK> FZCYK--GBK1-0 FZCaiYun-M09\n"
    "<方正彩云繁体> FZCaiYun-M09T FZCYFW FZCYFW—GB1-0\n"
    "<方正彩云简体> FZCaiYun-M09S FZCYJW FZCYJW—GB1-0\n"
    "<方正超粗黑_GBK> FZCCHK--GBK1-0 FZChaoCuHei-M10\n"
    "<方正超粗黑繁体> FZChaoCuHei-M10T FZCCHFW FZCCHFW—GB1-0\n"
    "<方正超粗黑简体> FZChaoCuHei-M10S FZCCHJW FZCCHJW—GB1-0\n"
    "<方正粗黑繁体> FZCuHei-B03T FZH4FW FZH4FW—GB1-0\n"
    "<方正粗活意_GBK> FZCHYK--GBK1-0 FZCuHuoYi-M25\n"
    "<方正粗活意繁体> FZCuHuoYi-M25T FZCHYFW—GB1-0 FZCHYFW\n"
    "<方正粗活意简体> FZCuHuoYi-M25S FZCHYJW—GB1-0 FZCHYJW\n"
    "<方正粗宋_GBK> FZCSK--GBK1-0 FZCuSong-B09\n"
    "<方正粗宋繁体> FZCuSong-B09T FZCSFW FZCSFW—GB1-0\n"
    "<方正粗宋简体> FZCuSong-B09S FZCSJW FZCSJW—GB1-0\n"
    "<方正粗圆_GBK> FZY4K--GBK1-0 FZCuYuan-M03\n"
    "<方正粗圆繁体> FZCuYuan-M03T FZY4FW FZY4FW—GB1-0\n"
    "<方正粗圆简体> FZCuYuan-M03S FZY4JW FZY4JW—GB1-0\n"
    "<方正粗倩_GBK> FZCQK--GBK1-0 FZCuQian-M17\n"
    "<方正粗倩繁体> FZCuQian-M17T FZCQFW FZCQFW—GB1-0\n"
    "<方正粗倩简体> FZCuQian-M17S FZCQJW FZCQJW—GB1-0\n"
    "<方正大标宋_GBK> FZDBSK--GBK1-0 FZDaBiaoSong-B06\n"
    "<方正大标宋繁体> FZDaBiaoSong-B06T FZDBSFW FZDBSFW—GB1-0\n"
    "<方正大标宋简体> FZDaBiaoSong-B06S FZDBSJW FZDBSJW—GB1-0\n"
    "<方正大黑_GBK> FZDHTK--GBK1-0 FZDaHei-B02\n"
    "<方正大黑繁体> FZDaHei-B02T FZDHTFW—GB1-0 FZDHTFW\n"
    "<方正大黑简体> FZDaHei-B02S FZDHTJW FZDHTJW—GB1-0\n"
    "<方正仿宋_GBK> FZFSK--GBK1-0 FZFangSong-Z02\n"
    "<方正仿宋繁体> FZFangSong-Z02T FZFSFW FZFSFW—GB1-0\n"
    "<方正仿宋简体> FZFangSong-Z02S FZFSJW FZFSJW—GB1-0\n"
    "<方正古隶_GBK> FZGLK--GBK1-0 FZGuLi-S12\n"
    "<方正古隶繁体> FZGuLi-S12T FZGLFW--GB1-0 FZGLFW\n"
    "<方正古隶简体> FZGuLi-S12S FZGLJW--GB1-0 FZGLJW\n"
    "<方正黑体_GBK> FZHTK--GBK1-0 FZHei-B01\n"
    "<方正黑体繁体> FZHei-B01T FZHTFW FZHTFW—GB1-0\n"
    "<方正黑体简体> FZHei-B01S FZHTJW FZHTJW—GB1-0\n"
    "<方正华隶_GBK> FZHLK--GBK1-0 FZHuaLi-M14\n"
    "<方正华隶繁体> FZHuaLi-M14T FZHLFW FZHLFW—GB1-0\n"
    "<方正华隶简体> FZHuaLi-M14S FZHLJW FZHLJW—GB1-0\n"
    "<方正黄草_GBK> FZHCK--GBK1-0 FZHuangCao-S09\n"
    "<方正黄草简体> FZHuangCao-S09S FZHCJW FZHCJW—GB1-0\n"
    "<方正剪纸_GBK> FZJZK--GBK1-0 FZJianZhi-M23\n"
    "<方正剪纸繁体> FZJianZhi-M23T FZJZFW—GB1-0 FZJZFW\n"
    "<方正剪纸简体> FZJianZhi-M23S FZJZJW—GB1-0 FZJZJW\n"
    "<方正卡通_GBK> FZKATK--GBK1-0 FZKaTong-M19\n"
    "<方正卡通繁体> FZKaTong-M19T FZKATFW--GB1-0 FZKATFW\n"
    "<方正卡通简体> FZKaTong-M19S FZKATJW--GB1-0 FZKATJW\n"
    "<方正楷体_GBK> FZKTK--GBK1-0 FZKai-Z03\n"
    "<方正楷体繁体> FZKai-Z03T FZKTFW FZKTFW—GB1-0\n"
    "<方正楷体简体> FZKai-Z03S FZKTJW FZKTJW—GB1-0\n"
    "<方正康体_GBK> FZKANGK--GBK1-0 FZKangTi-S07\n"
    "<方正康体繁体> FZKangTi-S07T FZKANGFW FZKANGFW—GB1-0\n"
    "<方正康体简体> FZKangTi-S07S FZKANGJW FZKANGJW—GB1-0\n"
    "<方正隶变_GBK> FZLBK--GBK1-0 FZLiBian-S02\n"
    "<方正隶变繁体> FZLiBian-S02T FZLBFW FZLBFW—GB1-0\n"
    "<方正隶变简体> FZLiBian-S02S FZLBJW FZLBJW—GB1-0\n"
    "<方正隶二_GBK> FZL2K--GBK1-0 FZLiShu II-S06\n"
    "<方正隶二繁体> FZLiShu II-S06T FZL2FW FZL2FW—GB1-0\n"
    "<方正隶二简体> FZLiShu II-S06S FZL2JW FZL2JW—GB1-0\n"
    "<方正隶书_GBK> FZLSK--GBK1-0 FZLiShu-S01\n"
    "<方正隶书繁体> FZLiShu-S01T FZLSFW—GB1-0 FZLSFW\n"
    "<方正隶书简体> FZLiShu-S01S FZLSJW FZLSJW—GB1-0\n"
    "<方正流行体_GBK> FZLXTK--GBK1-0 FZLiuXingTi-M26\n"
    "<方正流行体繁体> FZLiuXingTi-M26T FZLXTFW—GB1-0 FZLXTFW\n"
    "<方正流行体简体> FZLiuXingTi-M26S FZLXTJW—GB1-0 FZLXTJW\n"
    "<方正美黑_GBK> FZMHK--GBK1-0 FZMeiHei-M07\n"
    "<方正美黑简体> FZMeiHei-M07S FZMHJW FZMHJW—GB1-0\n"
    "<方正胖头鱼_GBK> FZPTYK--GBK1-0 FZPangTouYu-M24\n"
    "<方正胖头鱼简体> FZPangTouYu-M24S FZPTYJW—GB1-0 FZPTYJW\n"
    "<方正胖娃_GBK> FZPWK--GBK1-0 FZPangWa-M18\n"
    "<方正胖娃繁体> FZPangWa-M18T FZPWFW FZPWFW—GB1-0\n"
    "<方正胖娃简体> FZPangWa-M18S FZPWJW FZPWJW—GB1-0\n"
    "<方正平和_GBK> FZPHTK--GBK1-0 FZPingHe-S11\n"
    "<方正平和繁体> FZPingHe-S11T FZPHTFW FZPHTFW—GB1-0\n"
    "<方正平和简体> FZPingHe-S11S FZPHTJW FZPHTJW—GB1-0\n"
    "<方正平黑繁体> FZPingHei-B04T FZPHFW FZPHFW—GB1-0\n"
    "<方正启体_GBK> FZQTK--GBK1-0 FZQiTi-S14\n"
    "<方正启体繁体> FZQiTi-S14T FZQTFW--GB1-0 FZQTFW\n"
    "<方正启体简体> FZQiTi-S14S FZQTJW--GB1-0 FZQTJW\n"
    "<方正少儿_GBK> FZSEK--GBK1-0 FZShaoEr-M11\n"
    "<方正少儿繁体> FZShaoEr-M11T FZSEFW FZSEFW—GB1-0\n"
    "<方正少儿简体> FZShaoEr-M11S FZSEJW FZSEJW—GB1-0\n"
    "<方正瘦金书_GBK> FZSJSK--GBK1-0 FZShouJinShu-S10\n"
    "<方正瘦金书繁体> FZShouJinShu-S10T FZSJSFW FZSJSFW—GB1-0\n"
    "<方正瘦金书简体> FZShouJinShu-S10S FZSJSJW FZSJSJW—GB1-0\n"
    "<方正舒体> FZShuTi\n"
    "<方正舒体_GBK> FZSTK--GBK1-0 FZShuTi-S05\n"
    "<方正舒体繁体> FZShuTi-S05T FZSTFW FZSTFW—GB1-0\n"
    "<方正舒体简体> FZShuTi-S05S FZSTJW FZSTJW—GB1-0 7152\n"
    "<方正书宋_GBK> FZSSK--GBK1-0 FZShuSong-Z01\n"
    "<方正书宋繁体> FZShuSong-Z01T FZSSFW FZSSFW—GB1-0\n"
    "<方正书宋简体> FZShuSong-Z01S FZSSJW FZSSJW—GB1-0\n"
    "<方正水黑_GBK> FZSHHK--GBK1-0 FZShuiHei-M21\n"
    "<方正水黑繁体> FZShuiHei-M21T FZSHHFW--GB1-0 FZSHHFW\n"
    "<方正水黑简体> FZShuiHei-M21S FZSHHJW--GB1-0 FZSHHJW\n"
    "<方正水柱_GBK> FZSZK--GBK1-0 FZShuiZhu-M08\n"
    "<方正水柱繁体> FZShuiZhu-M08T FZSZFW FZSZFW—GB1-0\n"
    "<方正水柱简体> FZShuiZhu-M08S FZSZJW FZSZJW—GB1-0\n"
    "<方正宋黑_GBK> FZSHK--GBK1-0 FZSongHei-B07\n"
    "<方正宋黑繁体> FZSongHei-B07T FZSHFW—GB1-0 FZSHFW\n"
    "<方正宋黑简体> FZSongHei-B07S FZSHJW FZSHJW—GB1-0\n"
    "<方正宋三_GBK> FZS3K--GBK1-0 FZSong III-Z05\n"
    "<方正宋三简体> FZSong III-Z05S FZS3JW FZS3JW—GB1-0\n"
    "<方正宋一_GBK> FZSYK--GBK1-0 FZSongYi-Z13\n"
    "<方正宋一繁体> FZSongYi-Z13T FZSYFW FZSYFW—GB1-0\n"
    "<方正宋一简体> FZSongYi-Z13S FZSYJW FZSYJW—GB1-0\n"
    "<方正铁筋隶书_GBK> FZTJLSK--GBK1-0 FZTieJinLiShu-Z14\n"
    "<方正铁筋隶书繁体> FZTieJinLiShu-Z14T FZTJLSFW—GB1-0 FZTJLSFW\n"
    "<方正铁筋隶书简体> FZTieJinLiShu-Z14S FZTJLSJW—GB1-0 FZTJLSJW\n"
    "<方正魏碑_GBK> FZWBK--GBK1-0 FZWeiBei-S03\n"
    "<方正魏碑繁体> FZWeiBei-S03T FZWBFW FZWBFW—GB1-0\n"
    "<方正魏碑简体> FZWeiBei-S03S FZWBJW FZWBJW—GB1-0\n"
    "<方正细等线_GBK> FZXDXK--GBK1-0 FZXiDengXian-Z06\n"
    "<方正细等线简体> FZXiDengXian-Z06S FZXDXJW FZXDXJW—GB1-0\n"
    "<方正细黑一_GBK> FZXH1K--GBK1-0 FZXiHei I-Z08\n"
    "<方正细黑一繁体> FZXiHei I-Z08T FZXH1FW FZXH1FW—GB1-0\n"
    "<方正细黑一简体> FZXiHei I-Z08S FZXH1JW FZXH1JW—GB1-0\n"
    "<方正细珊瑚_GBK> FZXSHK--GBK1-0 FZXiShanHu-M13\n"
    "<方正细珊瑚繁体> FZXiShanHu-M13T FZXSHFW FZXSHFW—GB1-0\n"
    "<方正细珊瑚简体> FZXiShanHu-M13S FZXSHJW FZXSHJW—GB1-0\n"
    "<方正细圆_GBK> FZY1K--GBK1-0 FZXiYuan-M01\n"
    "<方正细圆繁体> FZXiYuan-M01T FZY1FW FZY1FW—GB1-0\n"
    "<方正细圆简体> FZXiYuan-M01S FZY1JW FZY1JW—GB1-0\n"
    "<方正细倩_GBK> FZXQK--GBK1-0 FZXiQian-M15\n"
    "<方正细倩繁体> FZXiQian-M15T FZXQFW FZXQFW—GB1-0\n"
    "<方正细倩简体> FZXiQian-M15S FZXQJW FZXQJW—GB1-0\n"
    "<方正祥隶_GBK> FZXIANGLK--GBK1-0 FZXIANGLi-S17\n"
    "<方正祥隶繁体> FZXiangLi-S17T FZXIANGLFW—GB1-0 FZXIANGLFW\n"
    "<方正祥隶简体> FZXiangLi-S17S FZXIANGLJW—GB1-0 FZXIANGLJW\n"
    "<方正小标宋_GBK> FZXBSK--GBK1-0 FZXiaoBiaoSong-B05\n"
    "<方正小标宋繁体> FZXiaoBiaoSong-B05T FZXBSFW FZXBSFW—GB1-0\n"
    "<方正小标宋简体> FZXiaoBiaoSong-B05S FZXBSJW FZXBSJW—GB1-0\n"
    "<方正小篆体> FZXiaoZhuanTi-S13T FZXZTFW--GB1-0 FZXZTFW\n"
    "<方正小篆体_GBK> FZXZTK--GBK1-0 FZXiaoZhuanTi-S13\n"
    "<方正新报宋_GBK> FZNBSK--GBK1-0 FZNew BaoSong-Z12\n"
    "<方正新报宋简体> FZNew BaoSong-Z12S FZNBSJW FZNBSJW—GB109\n"
    "<方正新舒体_GBK> FZNSTK--GBK1-0 FZNew ShuTi-S08\n"
    "<方正新舒体繁体> FZNew ShuTi-S08T FZNSTFW FZNSTFW—GB1-0\n"
    "<方正新舒体简体> FZNew ShuTi-S08S FZNSTJW FZNSTJW—GB1-0\n"
    "<方正新书宋繁体> FZNew ShuSong-Z10T FZXSSFW FZXSSFW—GB1-0\n"
    "<方正新秀丽繁体> FZNew XiuLi-Z11T FZXXLFW FZXXLFW—GB1-0\n"
    "<方正行楷_GBK> FZXKK--GBK1-0 FZXingKai-S04\n"
    "<方正行楷繁体> FZXingKai-S04T FZXKFW FZXKFW—GB1-0\n"
    "<方正行楷简体> FZXingKai-S04S FZXKJW FZXKJW—GB1-0\n"
    "<方正姚体> FZYaoti\n"
    "<方正姚体_GBK> FZYTK--GBK1-0 FZYaoTi-M06\n"
    "<方正姚体繁体> FZYaoTi-M06T FZYTFW FZYTFW—GB1-0\n"
    "<方正姚体简体> FZYaoTi-M06S FZYTJW FZYTJW—GB1-0\n"
    "<方正艺黑_GBK> FZYHK--GBK1-0 FZYiHei-M20\n"
    "<方正艺黑繁体> FZYiHei-M20T FZYHFW--GB1-0 FZYHFW\n"
    "<方正艺黑简体> FZYiHei-M20S FZYHJW--GB1-0 FZYHJW\n"
    "<方正硬笔楷书_GBK> FZYBKSK--GBK1-0 FZYingBiKaiShu-S15\n"
    "<方正硬笔楷书繁体> FZYingBiKaiShu-S15T FZYBKSFW--GB1-0 FZYBKSFW\n"
    "<方正硬笔楷书简体> FZYingBiKaiShu-S15S FZYBKSJW--GB1-0 FZYBKSJW\n"
    "<方正硬笔行书_GBK> FZYBXSK--GBK1-0 FZYingBiXingShu-S16\n"
    "<方正硬笔行书繁体> FZYingBiXingShu-S16T FZYBXSFW--GB1-0 FZYBXSFW\n"
    "<方正硬笔行书简体> FZYingBiXingShu-S16S FZYBXSJW--GB1-0 FZYBXSJW\n"
    "<方正幼线_GBK> FZYXK--GBK1-0 FZYouXian-Z09\n"
    "<方正幼线繁体> FZYouXian-Z09T FZYXFW FZYXFW—GB1-0\n"
    "<方正幼线简体> FZYouXian-Z09S FZYXJW--GB1-0 FZYXJW\n"
    "<方正毡笔黑_GBK> FZZBHK--GBK1-0 FZZhanBiHei-M22\n"
    "<方正毡笔黑繁体> FZZhanBiHei-M22T FZZBHFW--GB1-0 FZZBHFW\n"
    "<方正毡笔黑简体> FZZhanBiHei-M22S FZZBHJW--GB1-0 FZZBHJW\n"
    "<方正稚艺_GBK> FZZHYK--GBK1-0 FZZhiYi-M12\n"
    "<方正稚艺繁体> FZZhiYi-M12T FZZHYFW FZZHYFW—GB1-0\n"
    "<方正稚艺简体> FZZhiYi-M12S FZZHYJW FZZHYJW—GB1-0\n"
    "<方正中等线_GBK> FZZDXK--GBK1-0 FZZhongDengXian-Z07\n"
    "<方正中等线繁体> FZZhongDengXian-Z07T FZZDXFW FZZDXFW—GB1-0\n"
    "<方正中等线简体> FZZhongDengXian-Z07S FZZDXJW FZZDXJW—GB1-0\n"
    "<方正中楷繁体> FZZhongKai-B08T FZZKFW FZZKFW—GB1-0\n"
    "<方正中倩_GBK> FZZQK--GBK1-0 FZZhongQian-M16\n"
    "<方正中倩繁体> FZZhongQian-M16T FZZQFW FZZQFW—GB1-0\n"
    "<方正中倩简体> FZZhongQian-M16S FZZQJW FZZQJW—GB1-0\n"
    "<方正准圆_GBK> FZY3K--GBK1-0 FZZhunYuan-M02\n"
    "<方正准圆繁体> FZZhunYuan-M02T FZY3FW FZY3FW—GB1-0\n"
    "<方正准圆简体> FZZhunYuan-M02S FZY3JW FZY3JW—GB1-0\n"
    "<方正综艺_GBK> FZZYK--GBK1-0 FZZongYi-M05\n"
    "<方正综艺繁体> FZZongYi-M05T FZZYFW FZZYFW—GB1-0\n"
    "<方正综艺简体> FZZongYi-M05S FZZYJW FZZYJW—GB1-0\n"
    "<方正琥珀_GBK> FZHPK--GBK1-0 FZHuPo-M04\n"
    "<方正琥珀繁体> FZHuPo-M04T FZHPFW FZHPFW—GB1-0\n"
    "<方正琥珀简体> FZHuPo-M04S FZHPJW FZHPJW—GB1-0\n"
    "<仿宋> FangSong\n"
    "<仿宋_GB2312> FangSong_GB2312\n"
    "<汉仪白棋体简> HYM5GJ\n"
    "<汉仪柏青体繁> HYJ4GF\n"
    "<汉仪柏青体简> HYJ4GJ\n"
    "<汉仪报宋繁> HYA2GF\n"
    "<汉仪报宋简> HYA2GJ\n"
    "<汉仪彩蝶体简> HYK5GJ\n"
    "<汉仪彩云体繁> HYL1GF\n"
    "<汉仪彩云体简> HYL1GJ\n"
    "<汉仪长美黑繁> HYB3GF\n"
    "<汉仪长美黑简> HYB3GJ\n"
    "<汉仪长宋繁> HYA5GF\n"
    "<汉仪长宋简> HYA5GJ\n"
    "<汉仪长艺体繁> HYB6GF\n"
    "<汉仪长艺体简> HYB6GJ\n"
    "<汉仪超粗黑繁> HYB0GF\n"
    "<汉仪超粗黑简> HYB0GJ\n"
    "<汉仪超粗宋繁> HYA0GF\n"
    "<汉仪超粗宋简> HYA0GJ\n"
    "<汉仪超粗圆简> HYE0GJ\n"
    "<汉仪陈频破体简> HYF5GJ\n"
    "<汉仪粗仿宋简> HYD4GJ\n"
    "<汉仪粗黑繁> HYB9GF\n"
    "<汉仪粗黑简> HYB9GJ\n"
    "<汉仪粗宋繁> HYA9GF\n"
    "<汉仪粗宋简> HYA9GJ\n"
    "<汉仪粗圆繁> HYE4GF\n"
    "<汉仪粗圆简> HYE4GJ\n"
    "<汉仪粗篆繁> HYJ3GF\n"
    "<汉仪大黑繁> HYB2GF\n"
    "<汉仪大黑简> HYB2GJ\n"
    "<汉仪大隶书繁> HYF1GF\n"
    "<汉仪大隶书简> HYF1GJ\n"
    "<汉仪大宋繁> HYA4GF\n"
    "<汉仪大宋简> HYA4GJ\n"
    "<汉仪蝶语体简> HYN3GJ\n"
    "<汉仪方叠体繁> HYB4GF\n"
    "<汉仪方叠体简> HYB4GJ\n"
    "<汉仪方隶简> HYF0GJ\n"
    "<汉仪仿宋繁> HYD1GF\n"
    "<汉仪仿宋简> HYD1GJ\n"
    "<汉仪哈哈体简> HYM4GJ\n"
    "<汉仪海韵体简> HYK3GJ\n"
    "<汉仪黑棋体简> HYM6GJ\n"
    "<汉仪黑咪体繁> HYM2GF\n"
    "<汉仪黑咪体简> HYM2GJ\n"
    "<汉仪花蝶体简> HYF9GJ\n"
    "<汉仪火柴体简> HYQ2GJ\n"
    "<汉仪家书繁> HYD2GF\n"
    "<汉仪家书简> HYD2GJ\n"
    "<汉仪楷体繁> HYC1GF\n"
    "<汉仪楷体简> HYC1GJ\n"
    "<汉仪立黑简> HYT4GJ\n"
    "<汉仪菱心体简> HYK2GJ\n"
    "<汉仪凌波体繁> HYR1GF\n"
    "<汉仪凌波体简> HYR1GJ\n"
    "<汉仪萝卜体简> HYY2GJ\n"
    "<汉仪漫步体繁> HYR2GF\n"
    "<汉仪漫步体简> HYR2GJ\n"
    "<汉仪南宫体简> HYH4GJ\n"
    "<汉仪清韵体简> HYG4GJ\n"
    "<汉仪神工体简> HYH2GJ\n"
    "<汉仪瘦金书繁> HYI3GF\n"
    "<汉仪瘦金书简> HYI3GJ\n"
    "<汉仪舒同体繁> HYN1GF\n"
    "<汉仪舒同体简> HYN1GJ\n"
    "<汉仪书魂体简> HYH3GJ\n"
    "<汉仪书宋二繁> HYA6GF\n"
    "<汉仪书宋二简> HYA6GJ\n"
    "<汉仪书宋一繁> HYA1GF\n"
    "<汉仪书宋一简> HYA1GJ\n"
    "<汉仪双线体繁> HYB7GF\n"
    "<汉仪双线体简> HYB7GJ\n"
    "<汉仪水波体简> HYM7GJ\n"
    "<汉仪水滴体繁> HYP1GF\n"
    "<汉仪水滴体简> HYP1GJ\n"
    "<汉仪太极体简> HYO3GJ\n"
    "<汉仪特细等线简> HYG6GJ\n"
    "<汉仪娃娃篆简> HYJ2GJ\n"
    "<汉仪魏碑繁> HYH1GF\n"
    "<汉仪魏碑简> HYH1GJ\n"
    "<汉仪细等线繁> HYG1GF\n"
    "<汉仪细等线简> HYG1GJ\n"
    "<汉仪细行楷简> HYI2GJ\n"
    "<汉仪细圆繁> HYE1GF\n"
    "<汉仪细圆简> HYE1GJ\n"
    "<汉仪细中圆繁> HYE2GF\n"
    "<汉仪细中圆简> HYE2GJ\n"
    "<汉仪小隶书繁> HYF2GF\n"
    "<汉仪小隶书简> HYF2GJ\n"
    "<汉仪行楷繁> HYI1GF\n"
    "<汉仪行楷简> HYI1GJ\n"
    "<汉仪醒示体繁> HYB5GF\n"
    "<汉仪醒示体简> HYB5GJ\n"
    "<汉仪秀英体繁> HYY1GF\n"
    "<汉仪秀英体简> HYY1GJ\n"
    "<汉仪雪峰体繁> HYO2GF\n"
    "<汉仪雪峰体简> HYO2GJ\n"
    "<汉仪雪君体繁> HYI4GF\n"
    "<汉仪雪君体简> HYI4GJ\n"
    "<汉仪丫丫体简> HYG3GJ\n"
    "<汉仪颜楷繁> HYX4GF\n"
    "<汉仪雁翎体简> HYF4GJ\n"
    "<汉仪圆叠体繁> HYB8GF\n"
    "<汉仪圆叠体简> HYB8GJ\n"
    "<汉仪中等线繁> HYG2GF\n"
    "<汉仪中等线简> HYG2GJ\n"
    "<汉仪中黑繁> HYB1GF\n"
    "<汉仪中黑简> HYB1GJ\n"
    "<汉仪中楷简> HYC3GJ\n"
    "<汉仪中隶书繁> HYF3GF\n"
    "<汉仪中隶书简> HYF3GJ\n"
    "<汉仪中宋繁> HYA3GF\n"
    "<汉仪中宋简> HYA3GJ\n"
    "<汉仪中圆繁> HYE3GF\n"
    "<汉仪中圆简> HYE3GJ\n"
    "<汉仪竹节体繁> HYQ1GF\n"
    "<汉仪竹节体简> HYQ1GJ\n"
    "<汉仪篆书繁> HYJ1GF\n"
    "<汉仪字典宋繁> HYA7GF\n"
    "<汉仪字典宋简> HYA7GJ\n"
    "<汉仪综艺体繁> HYK1GF\n"
    "<汉仪综艺体简> HYK1GJ\n"
    "<汉仪咪咪体繁> HYM1GF\n"
    "<汉仪咪咪体简> HYM1GJ\n"
    "<汉仪嘟嘟体简> HYY4GJ\n"
    "<汉仪琥珀体繁> HYO1GF\n"
    "<汉仪琥珀体简> HYO1GJ\n"
    "<汉仪橄榄体繁> HYX1GF\n"
    "<汉仪橄榄体简> HYX1GJ\n"
    "<汉仪黛玉体简> HYR3GJ\n"
    "<黑体> SimHei\n"
    "<华文彩云> STCaiyun\n"
    "<华文仿宋> STFangsong\n"
    "<华文仿宋> STFangsong\n"
    "<华文黑体> STHeiti\n"
    "<华文楷体> STKaiti\n"
    "<华文楷体> STKaiti\n"
    "<华文隶书> STLiti\n"
    "<华文宋体> STSong\n"
    "<华文宋体> STSong\n"
    "<华文细黑> STHeiti Light STXihei\n"
    "<华文细黑> STXihei\n"
    "<华文新魏> STXinwei\n"
    "<华文行楷> STXingkai\n"
    "<华文中宋> STZhongsong\n"
    "<华文琥珀> STHupo\n"
    "<細明體> MingLiU\n"
    "<楷体> KaiTi\n"
    "<楷体_GB2312> KaiTi_GB2312\n"
    "<隶书> LiSu\n"
    "<宋体> SimSun\n"
    "<蘋果儷細宋> Apple LiSung Light\n"
    "<蘋果儷中黑> Apple LiGothic Medium\n"
    "<微软雅黑体> Microsoft YaHei\n"
    "<微軟正黑體> Microsoft JhengHei\n"
    "<文鼎ＰＯＰ－４> Pop4EG-Bold-GB GPOP05B\n"
    "<文鼎齿轮体> ChrluenEG-Medium-GB GCHR00M\n"
    "<文鼎齿轮体繁> ChrluenEG-Medium-T-GB TCHR00M\n"
    "<文鼎粗钢笔行楷> PensinkaiEG-Bold-GB GPSK00B\n"
    "<文鼎弹簧体> TanhuangEG-Bold-GB GTAN00B\n"
    "<文鼎雕刻体> DiaukeEG-Bold-GB GDIK00B\n"
    "<文鼎雕刻体繁> DiaukeEG-Bold-T-GB TDIK00B\n"
    "<文鼎胡子体> HutzEG-Extra-GB GHUT00E\n"
    "<文鼎花瓣体> HuabanEG-Ultra-GB GHUB00U\n"
    "<文鼎火柴体> HuochaiEG-Bold-GB GHUO00B\n"
    "<文鼎贱狗体> JiangouEG-Bold-GB GJIA00B\n"
    "<文鼎贱狗体繁> JiangouEG-Bold-T-GB TJIA00B\n"
    "<文鼎荆棘体> JingjiEG-Medium-GB GJIJ00M\n"
    "<文鼎荆棘体繁> JingjiEG-Medium-T-GB TJIJ00M\n"
    "<文鼎霹雳体> PiliEG-Ultra-GB GPIL00U\n"
    "<文鼎石头体> StoneEG-Extra-GB GSTO00E\n"
    "<文鼎谁的字体> SheideEG-Medium-GB GSHE00M\n"
    "<文鼎谁的字体繁> SheideEG-Medium-T-GB TSHE00M\n"
    "<文鼎水管体> ShueiguanEG-Bold-GB GSHG00B\n"
    "<文鼎习字体> YankaigungEG-Ultra-GB GYKG00U\n"
    "<文鼎细钢笔行楷> PensinkaiEG-Light-GB GPSK00L\n"
    "<文鼎香肠体> ShiangchangEG-Bold-GB GSHC00B\n"
    "<文鼎行楷碑体> SingkaibeiEG-Bold-GB GSKB00B\n"
    "<文鼎淹水体> YanshueiEG-Extra-GB GYAN00E\n"
    "<文鼎圆立体> YuanliEG-Bold-GB GYUL00B\n"
    "<文鼎中钢笔行楷> PensinkaiEG-Medium-GB GPSK00M\n"
    "<文鼎中特广告体> Pop3EG-Extra-GB GPOP03E\n"
    "<文鼎竹子体> JutzEG-Medium-GB GJUT00M\n"
    "<文鼎潇洒体> ShiansaEG-Medium-GB GSHS00M\n"
    "<文鼎妞妞体> NiuniuEG-Bold-GB GNIU00B\n"
    "<新細明體> PMingLiU\n"
    "<新宋体> NSimSun\n"
    "<幼圆> YouYuan\n";


#endif // PSDFONTS_H_INCLUDED
